### ISSUE TITLE
Improve OpenCV tracking functionality

### ISSUE THREAD

**Issue by azkevin** [azkevin/U-TRACKR#4]
Some current problems:

- [ ] Current implementation only tracks circles.

- [ ] Current implementation tracks only using HSV. This limits our tracking to lit areas, and objects that have vibrant colored markers.

- [ ] Small range of tracking; inconsistent when brought more than an arm's length away

A possible solution to the above is to use models. [This project](https://github.com/HackerHouseYT/Smart-Security-Camera) uses [predefined models](https://github.com/HackerHouseYT/Smart-Security-Camera/tree/master/models) to recognize human faces and bodies rather than HSV.
